logging:
  level: INFO
  loggers:
    com.pmonteiro: DEBUG

database:
  host: localhost
  port: 12345
  db: inmemory
  collection: tasks

swagger:
  includeSwaggerResource: true
  resourcePackage: com.pmonteiro.dropwizard.resources